### ISSUE TITLE
El repositorio es público

### ISSUE THREAD

**Issue by manueldeljesus** [parbol/SystematicClimate#1]
¿Hay algún problema en que tengamos el repositorio abierto de forma pública? Habitualmente los pongo en privado cuando van a ser la base de alguna investigación, pero igual soy un paranoias, así que te dejo la pregunta por aquí. 😄

**Comment by parbol** [comment]
Yo no tengo problema. Aunque tengo cuenta privada de github, así que si tienes preferencia lo hago privado.

**Comment by manueldeljesus** [comment]
Sin problema por mi parte tampoco, la verdad. Sólo preguntaba por ver cuál era tu opinión al respecto. Como hasta ahora todos los GitHub en que había colaborado eran privados, me había dado «vertigo» ver un repo público; nada más.
