### ISSUE TITLE
Verificar acceso a máquina IH

### ISSUE THREAD

**Issue by manueldeljesus** [parbol/SystematicClimate#2]
Tienes dos direcciones IP en el Whatsapp. Dime, por favor, si tienes acceso a ellas por ssh desde la VPN -tanto desde IFCA, como desde casa-. Debería pedirte credenciales nada más, porque de momento no hay cuenta configurada.

Gracias muchas

**Comment by parbol** [comment]
Hola Manu, sí, accedo sin problemas, por lo menos desde el IFCA.

**Comment by manueldeljesus** [comment]
Entiendo que a las dos direcciones. Si fuese que no, me dices; si es que sí, _no further action is required_.

Gracias mil

**Comment by parbol** [comment]
Sí, sí. Las dos direcciones, y aunque no he probado desde casa en realidad da igual: yo desde casa puedo entrar ssh a este ordenador desde el que he hecho la prueba en el IFCA, así que con 2 ssh puedo acceder seguro a esas dos ips.

**Comment by manueldeljesus** [comment]
**PERFECTO**

Me mola esto del GitHub 😄

**Comment by parbol** [comment]
Jejeje, es muy práctico la verdad :-)
